"use client";

import "./globals.css";
import type { Metadata } from "next";
import { RecoilRoot } from "recoil";
import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import { AuthProvider } from "./context/AuthContext"

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <AuthProvider>
          <header className="mb-12">
            <Box sx={{ flexGrow: 1 }}>
              <AppBar position="static">
                <Toolbar>
                  <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                    Todoリスト
                  </Typography>
                  {/* <Button color="inherit">Login</Button> */}
                </Toolbar>
              </AppBar>
            </Box>
          </header>
          <RecoilRoot>
            {children}
          </RecoilRoot>
        </AuthProvider>
      </body>
    </html>
  );
}